---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: mcdgorderer
  name: orderer-mcdgorderer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: hyperledger
        role: orderer
        org: mcdgorderer
        orderer-id: orderer
    spec:
      containers:
      - name: orderer-mcdgorderer
        image: hyperledger/fabric-orderer:x86_64-1.1.0-rc1
        env:
        - name: ORDERER_GENERAL_LOGLEVEL
          value: debug
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /var/hyperledger/orderer/orderer.genesis.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: McdgOrdererOrgMSP
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /var/hyperledger/orderer/msp
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "false"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /var/hyperledger/orderer/tls/server.key
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /var/hyperledger/orderer/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: '[/var/hyperledger/orderer/tls/ca.crt]'
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        ports:
         - containerPort: 7050
        command: ["orderer"]
        volumeMounts:
         - mountPath: /var/hyperledger/orderer/msp
           name: orderer-ca
           #subPath: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp
           subPath: orderer/msp
         - mountPath: /var/hyperledger/orderer/tls
           name: orderer-ca
           #subPath: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/
           subPath: orderer/tls
         - mountPath: /var/hyperledger/orderer/orderer.genesis.block
           name: orderer-artifacts
           subPath: genesis.block
      volumes:
       - name: orderer-ca
         persistentVolumeClaim:
             claimName: mcdgorderer-pvc
       - name: orderer-artifacts
         persistentVolumeClaim:
             claimName: mcdgorderer-artifacts-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: orderer
  namespace: mcdgorderer
spec:
 selector:
   app: hyperledger
   role: orderer
   orderer-id: orderer
   org: mcdgorderer
 type: NodePort
 ports:
   - name: listen-endpoint
     protocol: TCP
     port: 7050
     targetPort: 7050
     nodePort: 32301