---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mcdgordererconfig-pv
  labels:
    pv-name: mcdgordererconfig-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: fs-e0c93099.efs.us-east-2.amazonaws.com
    path: /mcdg
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: mcdgorderer
  name: mcdgordererconfig-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  selector:
    matchLabels:
      pv-name: mcdgordererconfig-pv
  resources:
    requests:
      storage: 10Mi

