apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: mcdgorderer
  name:	peer0-orderer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
       app: hyperledger
       role: peer
       peer-id: peer0
       org: mcdgorderer
    spec:
      containers:
      - name: couchdb
        image: hyperledger/fabric-couchdb:x86_64-1.1.0-preview
        ports:
         - containerPort: 5984


      - name: peer0-orderer
        image: hyperledger/fabric-peer:x86_64-1.1.0-rc1
        env:
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "localhost:5984"
        - name: CORE_VM_ENDPOINT
          value: "unix:///host/var/run/docker.sock"
        - name: CORE_LOGGING_LEVEL
          value: "DEBUG"
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: "/etc/hyperledger/fabric/tls/server.crt"
        - name: CORE_PEER_TLS_KEY_FILE
          value: "/etc/hyperledger/fabric/tls/server.key"
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: "/etc/hyperledger/fabric/tls/ca.crt"
        - name: CORE_PEER_ID
          value: peer0.mcdgorderer
        - name: CORE_PEER_ADDRESS
          value: peer0.mcdgorderer:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: peer0.mcdgorderer:7051
        - name: CORE_PEER_LOCALMSPID
          value: McdgClientOrgMSP
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: 0.0.0.0:7052
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        ports:
         - containerPort: 7051
         - containerPort: 7052
         - containerPort: 7053
        command: ["peer"]
        args: ["node","start"]
        volumeMounts:
         - mountPath: /etc/hyperledger/fabric/msp
           name: orderer-ca
           subPath: peer0/msp
         - mountPath: /etc/hyperledger/fabric/tls
           name: orderer-ca
           subPath: peer0/tls
         - mountPath: /etc/hyperledger/fabric
           name: orderer-ca
           subPath: peer0
         - mountPath: /var/hyperledger/orderer/orderer.genesis.block
           name: orderer-artifacts
           subPath: genesis.block
         - mountPath: /host/var/run/
           name: run
      volumes:
       - name: orderer-ca
         persistentVolumeClaim:
             claimName: mcdgorderer-pvc
       - name: orderer-artifacts
         persistentVolumeClaim:
             claimName: mcdgorderer-artifacts-pvc
       - name: run
         hostPath:
           path: /run

---
apiVersion: v1
kind: Service
metadata:
   namespace: mcdgorderer
   name: peer0
spec:
 selector:
   app: hyperledger
   role: peer
   peer-id: peer0
   org: mcdgorderer
 type: NodePort
 ports:
   - name: externale-listen-endpoint
     protocol: TCP
     port: 7051
     targetPort: 7051
     nodePort: 30003

   - name: chaincode-listen
     protocol: TCP
     port: 7052
     targetPort: 7052
     nodePort: 30004

---